# Задание 1
## Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [35]:
N = int(input('Введите число '))
a = np.arange(0, N)
a[::-1]

Введите число 9


array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
## Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [50]:
N = int(input('Введите число '))
a = np.diag(np.arange(N, 0, -1))
print(sum(sum(a)))

Введите число 9
45


# Задание 3
## Решите систему уравнений:
## 4x + 2y + z = 4
## x + 3y = 12
## 5y + 4z = -3

In [69]:
from numpy import linalg

In [70]:
c = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [71]:
d = np.array( [4, 12, -3] )

In [72]:
linalg.solve(c, d)

array([ 0.46666667,  3.84444444, -5.55555556])

In [73]:
np.allclose( np.dot(c, linalg.solve(c, d)), d )

True

# Задание 4
## Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [74]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [75]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [83]:
def cosine(users_stats, next_user_stats):
    users_statsLength = np.linalg.norm(users_stats)
    next_user_statsLength = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / (users_statsLength * next_user_statsLength)

In [84]:
e = np.array([cosine(row, next_user_stats) for row in users_stats])

In [85]:
e

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])